-- GENERATED by codegen/generate.js — do not edit by hand.
module Tebru.Box.GridCols exposing (lgCols, mdCols, smCols, xlCols)

{-| The responsive grid-cols matrix `Tebru.Box` resolves `withGridCols` through.
Each breakpoint fn is a closed case over 1..12 returning a literal class including
its breakpoint prefix (out of range falls back to a single column).

@docs lgCols, mdCols, smCols, xlCols

-}



smCols : Int -> String
smCols n =
    case n of
        1 ->
            "grid-cols-1"

        2 ->
            "grid-cols-2"

        3 ->
            "grid-cols-3"

        4 ->
            "grid-cols-4"

        5 ->
            "grid-cols-5"

        6 ->
            "grid-cols-6"

        7 ->
            "grid-cols-7"

        8 ->
            "grid-cols-8"

        9 ->
            "grid-cols-9"

        10 ->
            "grid-cols-10"

        11 ->
            "grid-cols-11"

        12 ->
            "grid-cols-12"

        _ ->
            "grid-cols-1"

mdCols : Int -> String
mdCols n =
    case n of
        1 ->
            "md:grid-cols-1"

        2 ->
            "md:grid-cols-2"

        3 ->
            "md:grid-cols-3"

        4 ->
            "md:grid-cols-4"

        5 ->
            "md:grid-cols-5"

        6 ->
            "md:grid-cols-6"

        7 ->
            "md:grid-cols-7"

        8 ->
            "md:grid-cols-8"

        9 ->
            "md:grid-cols-9"

        10 ->
            "md:grid-cols-10"

        11 ->
            "md:grid-cols-11"

        12 ->
            "md:grid-cols-12"

        _ ->
            "md:grid-cols-1"

lgCols : Int -> String
lgCols n =
    case n of
        1 ->
            "lg:grid-cols-1"

        2 ->
            "lg:grid-cols-2"

        3 ->
            "lg:grid-cols-3"

        4 ->
            "lg:grid-cols-4"

        5 ->
            "lg:grid-cols-5"

        6 ->
            "lg:grid-cols-6"

        7 ->
            "lg:grid-cols-7"

        8 ->
            "lg:grid-cols-8"

        9 ->
            "lg:grid-cols-9"

        10 ->
            "lg:grid-cols-10"

        11 ->
            "lg:grid-cols-11"

        12 ->
            "lg:grid-cols-12"

        _ ->
            "lg:grid-cols-1"

xlCols : Int -> String
xlCols n =
    case n of
        1 ->
            "xl:grid-cols-1"

        2 ->
            "xl:grid-cols-2"

        3 ->
            "xl:grid-cols-3"

        4 ->
            "xl:grid-cols-4"

        5 ->
            "xl:grid-cols-5"

        6 ->
            "xl:grid-cols-6"

        7 ->
            "xl:grid-cols-7"

        8 ->
            "xl:grid-cols-8"

        9 ->
            "xl:grid-cols-9"

        10 ->
            "xl:grid-cols-10"

        11 ->
            "xl:grid-cols-11"

        12 ->
            "xl:grid-cols-12"

        _ ->
            "xl:grid-cols-1"
