-- GENERATED by codegen/generate.js — do not edit by hand.
module Tebru.Theme.Border exposing (Border(..), borderToClass, withBorder, withBorderCustom)

{-| Generated token module — do not edit by hand.
To change a token, edit the tokens file and regenerate (codegen/generate.js).

@docs Border, borderToClass, withBorder, withBorderCustom

-}

import Tebru.Theme.Config as Config exposing (Config)


type Border a
    = Default
    | Hover
    | Divider
    | Focus
    | Error
    | Success
    | Transparent
    | OnDark
    | Custom a

borderToClass : (a -> String) -> Border a -> String
borderToClass toCustom v =
    case v of
        Default ->
            "border-border-default"

        Hover ->
            "border-border-hover"

        Divider ->
            "border-border-divider"

        Focus ->
            "border-border-focus"

        Error ->
            "border-border-error"

        Success ->
            "border-border-success"

        Transparent ->
            "border-border-transparent"

        OnDark ->
            "border-border-on-dark"

        Custom a ->
            toCustom a

withBorderCustom : (a -> String) -> Border a -> Config tag -> Config tag
withBorderCustom toCustom v =
    Config.set "border" (borderToClass toCustom v)


withBorder : Border Never -> Config tag -> Config tag
withBorder =
    withBorderCustom never
