-- GENERATED by codegen/generate.js — do not edit by hand.
module Tebru.Theme.Elevation exposing (Elevation(..), elevationToClass, withElevation, withElevationCustom)

{-| Generated token module — do not edit by hand.
To change a token, edit the tokens file and regenerate (codegen/generate.js).

@docs Elevation, elevationToClass, withElevation, withElevationCustom

-}

import Tebru.Theme.Config as Config exposing (Config)


type Elevation a
    = None
    | Xs
    | Sm
    | Md
    | Lg
    | Xl
    | Xxl
    | Custom a

elevationToClass : (a -> String) -> Elevation a -> String
elevationToClass toCustom v =
    case v of
        None ->
            "shadow-none"

        Xs ->
            "shadow-xs"

        Sm ->
            "shadow-sm"

        Md ->
            "shadow-md"

        Lg ->
            "shadow-lg"

        Xl ->
            "shadow-xl"

        Xxl ->
            "shadow-xxl"

        Custom a ->
            toCustom a

withElevationCustom : (a -> String) -> Elevation a -> Config tag -> Config tag
withElevationCustom toCustom v =
    Config.set "elevation" (elevationToClass toCustom v)


withElevation : Elevation Never -> Config tag -> Config tag
withElevation =
    withElevationCustom never
