-- GENERATED by codegen/generate.js — do not edit by hand.
module Tebru.Theme.MaxWidth exposing (MaxWidth(..), maxWidthToClass, withMaxWidth)

{-| Generated token module — do not edit by hand.
To change a token, edit the tokens file and regenerate (codegen/generate.js).

@docs MaxWidth, maxWidthToClass, withMaxWidth

-}

import Tebru.Theme.Config as Config exposing (Config)


type MaxWidth
    = X3s
    | X2s
    | Xs
    | Sm
    | Md
    | Lg
    | Xl
    | X2l
    | X3l
    | X4l
    | X5l
    | X6l
    | X7l

maxWidthToClass : MaxWidth -> String
maxWidthToClass v =
    case v of
        X3s ->
            "max-w-3xs"

        X2s ->
            "max-w-2xs"

        Xs ->
            "max-w-xs"

        Sm ->
            "max-w-sm"

        Md ->
            "max-w-md"

        Lg ->
            "max-w-lg"

        Xl ->
            "max-w-xl"

        X2l ->
            "max-w-2xl"

        X3l ->
            "max-w-3xl"

        X4l ->
            "max-w-4xl"

        X5l ->
            "max-w-5xl"

        X6l ->
            "max-w-6xl"

        X7l ->
            "max-w-7xl"

withMaxWidth : MaxWidth -> Config Config.Standard -> Config Config.Standard
withMaxWidth v =
    Config.set "max-width" (maxWidthToClass v)
