-- GENERATED by codegen/generate.js — do not edit by hand.
module Tebru.Theme.Radius exposing (Radius(..), radiusToClass, withRadius, withRadiusCustom, Corner(..), withRadiusCorner, withRadiusTop, withRadiusBottom)

{-| Generated token module — do not edit by hand.
To change a token, edit the tokens file and regenerate (codegen/generate.js).

@docs Radius, radiusToClass, withRadius, withRadiusCustom, Corner, withRadiusCorner, withRadiusTop
@docs withRadiusBottom

-}

import Tebru.Theme.Config as Config exposing (Config)


type Radius a
    = None
    | Sm
    | Md
    | Lg
    | Xl
    | Full
    | Custom a

radiusToClass : (a -> String) -> Radius a -> String
radiusToClass toCustom v =
    case v of
        None ->
            "rounded-none"

        Sm ->
            "rounded-sm"

        Md ->
            "rounded-md"

        Lg ->
            "rounded-lg"

        Xl ->
            "rounded-xl"

        Full ->
            "rounded-full"

        Custom a ->
            toCustom a

withRadiusCustom : (a -> String) -> Radius a -> Config Config.Standard -> Config Config.Standard
withRadiusCustom toCustom v =
    Config.set "radius" (radiusToClass toCustom v)


withRadius : Radius Never -> Config Config.Standard -> Config Config.Standard
withRadius =
    withRadiusCustom never

type Corner
    = TopLeft
    | TopRight
    | BottomLeft
    | BottomRight

cornerRadiusClass : Corner -> Radius Never -> String
cornerRadiusClass corner v =
    case ( corner, v ) of
        ( TopLeft, None ) ->
            "rounded-tl-none"

        ( TopLeft, Sm ) ->
            "rounded-tl-sm"

        ( TopLeft, Md ) ->
            "rounded-tl-md"

        ( TopLeft, Lg ) ->
            "rounded-tl-lg"

        ( TopLeft, Xl ) ->
            "rounded-tl-xl"

        ( TopLeft, Full ) ->
            "rounded-tl-full"

        ( TopRight, None ) ->
            "rounded-tr-none"

        ( TopRight, Sm ) ->
            "rounded-tr-sm"

        ( TopRight, Md ) ->
            "rounded-tr-md"

        ( TopRight, Lg ) ->
            "rounded-tr-lg"

        ( TopRight, Xl ) ->
            "rounded-tr-xl"

        ( TopRight, Full ) ->
            "rounded-tr-full"

        ( BottomLeft, None ) ->
            "rounded-bl-none"

        ( BottomLeft, Sm ) ->
            "rounded-bl-sm"

        ( BottomLeft, Md ) ->
            "rounded-bl-md"

        ( BottomLeft, Lg ) ->
            "rounded-bl-lg"

        ( BottomLeft, Xl ) ->
            "rounded-bl-xl"

        ( BottomLeft, Full ) ->
            "rounded-bl-full"

        ( BottomRight, None ) ->
            "rounded-br-none"

        ( BottomRight, Sm ) ->
            "rounded-br-sm"

        ( BottomRight, Md ) ->
            "rounded-br-md"

        ( BottomRight, Lg ) ->
            "rounded-br-lg"

        ( BottomRight, Xl ) ->
            "rounded-br-xl"

        ( BottomRight, Full ) ->
            "rounded-br-full"

        ( _, Custom a ) ->
            never a

withRadiusCorner : Corner -> Radius Never -> Config Config.Standard -> Config Config.Standard
withRadiusCorner corner v =
    Config.set (cornerSetKey corner) (cornerRadiusClass corner v)

cornerSetKey : Corner -> String
cornerSetKey corner =
    case corner of
        TopLeft ->
            "radius-tl"

        TopRight ->
            "radius-tr"

        BottomLeft ->
            "radius-bl"

        BottomRight ->
            "radius-br"

withRadiusTop : Radius Never -> Config Config.Standard -> Config Config.Standard
withRadiusTop v =
    withRadiusCorner TopLeft v >> withRadiusCorner TopRight v

withRadiusBottom : Radius Never -> Config Config.Standard -> Config Config.Standard
withRadiusBottom v =
    withRadiusCorner BottomLeft v >> withRadiusCorner BottomRight v
