-- GENERATED by codegen/generate.js — do not edit by hand.
module Tebru.Theme.Space exposing (Space(..), Edge(..), spaceClass)

{-| Generated token module — do not edit by hand.
To change a token, edit the tokens file and regenerate (codegen/generate.js).

@docs Space, Edge, spaceClass

-}



type Space
    = None
    | Xs
    | Xxs
    | Sm
    | Md
    | Lg
    | Xl
    | Xxl
    | Xxxl

type Edge
    = All
    | Top
    | Right
    | Bottom
    | Left
    | Px
    | Py
    | Gap
    | GapX
    | GapY

spaceClass : Edge -> Space -> String
spaceClass edge v =
    case ( edge, v ) of
        ( All, None ) ->
            "p-0"

        ( All, Xs ) ->
            "p-xs"

        ( All, Xxs ) ->
            "p-xxs"

        ( All, Sm ) ->
            "p-sm"

        ( All, Md ) ->
            "p-md"

        ( All, Lg ) ->
            "p-lg"

        ( All, Xl ) ->
            "p-xl"

        ( All, Xxl ) ->
            "p-xxl"

        ( All, Xxxl ) ->
            "p-xxxl"

        ( Top, None ) ->
            "pt-0"

        ( Top, Xs ) ->
            "pt-xs"

        ( Top, Xxs ) ->
            "pt-xxs"

        ( Top, Sm ) ->
            "pt-sm"

        ( Top, Md ) ->
            "pt-md"

        ( Top, Lg ) ->
            "pt-lg"

        ( Top, Xl ) ->
            "pt-xl"

        ( Top, Xxl ) ->
            "pt-xxl"

        ( Top, Xxxl ) ->
            "pt-xxxl"

        ( Right, None ) ->
            "pr-0"

        ( Right, Xs ) ->
            "pr-xs"

        ( Right, Xxs ) ->
            "pr-xxs"

        ( Right, Sm ) ->
            "pr-sm"

        ( Right, Md ) ->
            "pr-md"

        ( Right, Lg ) ->
            "pr-lg"

        ( Right, Xl ) ->
            "pr-xl"

        ( Right, Xxl ) ->
            "pr-xxl"

        ( Right, Xxxl ) ->
            "pr-xxxl"

        ( Bottom, None ) ->
            "pb-0"

        ( Bottom, Xs ) ->
            "pb-xs"

        ( Bottom, Xxs ) ->
            "pb-xxs"

        ( Bottom, Sm ) ->
            "pb-sm"

        ( Bottom, Md ) ->
            "pb-md"

        ( Bottom, Lg ) ->
            "pb-lg"

        ( Bottom, Xl ) ->
            "pb-xl"

        ( Bottom, Xxl ) ->
            "pb-xxl"

        ( Bottom, Xxxl ) ->
            "pb-xxxl"

        ( Left, None ) ->
            "pl-0"

        ( Left, Xs ) ->
            "pl-xs"

        ( Left, Xxs ) ->
            "pl-xxs"

        ( Left, Sm ) ->
            "pl-sm"

        ( Left, Md ) ->
            "pl-md"

        ( Left, Lg ) ->
            "pl-lg"

        ( Left, Xl ) ->
            "pl-xl"

        ( Left, Xxl ) ->
            "pl-xxl"

        ( Left, Xxxl ) ->
            "pl-xxxl"

        ( Px, None ) ->
            "px-0"

        ( Px, Xs ) ->
            "px-xs"

        ( Px, Xxs ) ->
            "px-xxs"

        ( Px, Sm ) ->
            "px-sm"

        ( Px, Md ) ->
            "px-md"

        ( Px, Lg ) ->
            "px-lg"

        ( Px, Xl ) ->
            "px-xl"

        ( Px, Xxl ) ->
            "px-xxl"

        ( Px, Xxxl ) ->
            "px-xxxl"

        ( Py, None ) ->
            "py-0"

        ( Py, Xs ) ->
            "py-xs"

        ( Py, Xxs ) ->
            "py-xxs"

        ( Py, Sm ) ->
            "py-sm"

        ( Py, Md ) ->
            "py-md"

        ( Py, Lg ) ->
            "py-lg"

        ( Py, Xl ) ->
            "py-xl"

        ( Py, Xxl ) ->
            "py-xxl"

        ( Py, Xxxl ) ->
            "py-xxxl"

        ( Gap, None ) ->
            "gap-0"

        ( Gap, Xs ) ->
            "gap-xs"

        ( Gap, Xxs ) ->
            "gap-xxs"

        ( Gap, Sm ) ->
            "gap-sm"

        ( Gap, Md ) ->
            "gap-md"

        ( Gap, Lg ) ->
            "gap-lg"

        ( Gap, Xl ) ->
            "gap-xl"

        ( Gap, Xxl ) ->
            "gap-xxl"

        ( Gap, Xxxl ) ->
            "gap-xxxl"

        ( GapX, None ) ->
            "gap-x-0"

        ( GapX, Xs ) ->
            "gap-x-xs"

        ( GapX, Xxs ) ->
            "gap-x-xxs"

        ( GapX, Sm ) ->
            "gap-x-sm"

        ( GapX, Md ) ->
            "gap-x-md"

        ( GapX, Lg ) ->
            "gap-x-lg"

        ( GapX, Xl ) ->
            "gap-x-xl"

        ( GapX, Xxl ) ->
            "gap-x-xxl"

        ( GapX, Xxxl ) ->
            "gap-x-xxxl"

        ( GapY, None ) ->
            "gap-y-0"

        ( GapY, Xs ) ->
            "gap-y-xs"

        ( GapY, Xxs ) ->
            "gap-y-xxs"

        ( GapY, Sm ) ->
            "gap-y-sm"

        ( GapY, Md ) ->
            "gap-y-md"

        ( GapY, Lg ) ->
            "gap-y-lg"

        ( GapY, Xl ) ->
            "gap-y-xl"

        ( GapY, Xxl ) ->
            "gap-y-xxl"

        ( GapY, Xxxl ) ->
            "gap-y-xxxl"
