-- GENERATED by codegen/generate.js — do not edit by hand.
module Tebru.Theme.Structure exposing (AspectRatio(..), BorderStyle(..), BorderWidth(..), Cursor(..), Display(..), Flex(..), FlexAlign(..), FlexBasis(..), FlexJustify(..), Inset(..), Opacity(..), Overflow(..), PointerEvents(..), Position(..), Size(..), ZLayer(..), controlSquare, square, withAlign, withAspectRatio, withBorderSide, withBorderStyle, withBorderWidth, withCenterX, withControlHeight, withCursor, withDisplay, withFlex, withFlexBasis, withFlexWrap, withGrow, withHeight, withInset, withJustify, withMaxWidth, withMinHeight, withMinWidth, withOpacity, withOverflow, withOverflowX, withOverflowY, withPointerEvents, withPosition, withShrink, withWidth, withZ)

{-| Structural styling — display, flex behavior, position, sizing, border structure, and friends.
The structural-enum bucket of the styling model: closed typed enums over stock Tailwind utility classes (var-less; no @theme tokens).

@docs AspectRatio, BorderStyle, BorderWidth, Cursor, Display, Flex, FlexAlign, FlexBasis, FlexJustify, Inset
@docs Opacity, Overflow, PointerEvents, Position, Size, ZLayer, controlSquare, square, withAlign
@docs withAspectRatio, withBorderSide, withBorderStyle, withBorderWidth, withCenterX, withControlHeight
@docs withCursor, withDisplay, withFlex, withFlexBasis, withFlexWrap, withGrow, withHeight, withInset
@docs withJustify, withMaxWidth, withMinHeight, withMinWidth, withOpacity, withOverflow, withOverflowX
@docs withOverflowY, withPointerEvents, withPosition, withShrink, withWidth, withZ

-}

import Tebru.Theme.Config as Config exposing (Config)
import Tebru.Theme.Space as Space exposing (Edge)


type BorderStyle
    = BorderSolid
    | BorderDashed
    | BorderDotted

withBorderStyle : BorderStyle -> Config tag -> Config tag
withBorderStyle v =
    Config.set "border-style"
        (case v of
            BorderSolid ->
                "border-solid"

            BorderDashed ->
                "border-dashed"

            BorderDotted ->
                "border-dotted"
        )

type Display
    = Block
    | Flex
    | InlineFlex
    | InlineBlock
    | Grid
    | None

withDisplay : Display -> Config Config.Standard -> Config Config.Standard
withDisplay v =
    Config.set "display"
        (case v of
            Block ->
                "block"

            Flex ->
                "flex"

            InlineFlex ->
                "inline-flex"

            InlineBlock ->
                "inline-block"

            Grid ->
                "grid"

            None ->
                "hidden"
        )

type FlexJustify
    = JustifyStart
    | JustifyCenter
    | JustifyEnd
    | JustifyBetween

withJustify : FlexJustify -> Config Config.Standard -> Config Config.Standard
withJustify v =
    Config.set "justify"
        (case v of
            JustifyStart ->
                "justify-start"

            JustifyCenter ->
                "justify-center"

            JustifyEnd ->
                "justify-end"

            JustifyBetween ->
                "justify-between"
        )

type FlexAlign
    = AlignStart
    | AlignCenter
    | AlignEnd
    | AlignStretch

withAlign : FlexAlign -> Config Config.Standard -> Config Config.Standard
withAlign v =
    Config.set "align"
        (case v of
            AlignStart ->
                "items-start"

            AlignCenter ->
                "items-center"

            AlignEnd ->
                "items-end"

            AlignStretch ->
                "items-stretch"
        )

type Cursor
    = CursorPointer
    | CursorDefault
    | CursorGrab
    | CursorNsResize

withCursor : Cursor -> Config Config.Standard -> Config Config.Standard
withCursor v =
    Config.set "cursor"
        (case v of
            CursorPointer ->
                "cursor-pointer"

            CursorDefault ->
                "cursor-default"

            CursorGrab ->
                "cursor-grab"

            CursorNsResize ->
                "cursor-ns-resize"
        )

type Position
    = Static
    | Relative
    | Absolute
    | Fixed
    | Sticky

withPosition : Position -> Config Config.Standard -> Config Config.Standard
withPosition v =
    Config.set "position"
        (case v of
            Static ->
                "static"

            Relative ->
                "relative"

            Absolute ->
                "absolute"

            Fixed ->
                "fixed"

            Sticky ->
                "sticky"
        )

type Inset
    = Inset0
    | InsetAuto

withInset : Inset -> Config Config.Standard -> Config Config.Standard
withInset v =
    Config.set "inset"
        (case v of
            Inset0 ->
                "inset-0"

            InsetAuto ->
                "inset-auto"
        )

type ZLayer
    = ZBase
    | ZRaised
    | ZSticky
    | ZDropdown
    | ZOverlay
    | ZModal

withZ : ZLayer -> Config Config.Standard -> Config Config.Standard
withZ v =
    Config.set "z"
        (case v of
            ZBase ->
                "z-0"

            ZRaised ->
                "z-10"

            ZSticky ->
                "z-20"

            ZDropdown ->
                "z-30"

            ZOverlay ->
                "z-40"

            ZModal ->
                "z-50"
        )

{-| Element opacity. A small generic scale (the stock Tailwind rungs the app
actually uses) — opacity is a structural property, not design-language colour,
so it lives here rather than in an app token.
-}
type Opacity
    = Opacity0
    | Opacity50
    | Opacity60
    | Opacity100

withOpacity : Opacity -> Config Config.Standard -> Config Config.Standard
withOpacity v =
    Config.set "opacity"
        (case v of
            Opacity0 ->
                "opacity-0"

            Opacity50 ->
                "opacity-50"

            Opacity60 ->
                "opacity-60"

            Opacity100 ->
                "opacity-100"
        )

type Overflow
    = OverflowVisible
    | OverflowHidden
    | OverflowAuto
    | OverflowScroll

withOverflow : Overflow -> Config Config.Standard -> Config Config.Standard
withOverflow v =
    Config.set "overflow"
        (case v of
            OverflowVisible ->
                "overflow-visible"

            OverflowHidden ->
                "overflow-hidden"

            OverflowAuto ->
                "overflow-auto"

            OverflowScroll ->
                "overflow-scroll"
        )

withOverflowX : Overflow -> Config Config.Standard -> Config Config.Standard
withOverflowX v =
    Config.set "overflow-x"
        (case v of
            OverflowVisible ->
                "overflow-x-visible"

            OverflowHidden ->
                "overflow-x-hidden"

            OverflowAuto ->
                "overflow-x-auto"

            OverflowScroll ->
                "overflow-x-scroll"
        )

withOverflowY : Overflow -> Config Config.Standard -> Config Config.Standard
withOverflowY v =
    Config.set "overflow-y"
        (case v of
            OverflowVisible ->
                "overflow-y-visible"

            OverflowHidden ->
                "overflow-y-hidden"

            OverflowAuto ->
                "overflow-y-auto"

            OverflowScroll ->
                "overflow-y-scroll"
        )

type PointerEvents
    = PointerNone
    | PointerAuto

withPointerEvents : PointerEvents -> Config Config.Standard -> Config Config.Standard
withPointerEvents v =
    Config.set "pointer-events"
        (case v of
            PointerNone ->
                "pointer-events-none"

            PointerAuto ->
                "pointer-events-auto"
        )

type Flex
    = Flex1
    | FlexAuto
    | FlexInitial
    | FlexNone

withFlex : Flex -> Config Config.Standard -> Config Config.Standard
withFlex v =
    Config.set "flex"
        (case v of
            Flex1 ->
                "flex-1"

            FlexAuto ->
                "flex-auto"

            FlexInitial ->
                "flex-initial"

            FlexNone ->
                "flex-none"
        )

type Size
    = SizeFull
    | SizeAuto
    | SizeScreen
    | SizeFit
    | SizeMin
    | SizeMax
    | SizeZero
    | S1_5
    | S3
    | S4
    | S6
    | S7
    | S9
    | S10
    | S11
    | S12
    | S14
    | S16
    | S20

withWidth : Size -> Config Config.Standard -> Config Config.Standard
withWidth v =
    Config.set "width"
        (case v of
            SizeFull ->
                "w-full"

            SizeAuto ->
                "w-auto"

            SizeScreen ->
                "w-screen"

            SizeFit ->
                "w-fit"

            SizeMin ->
                "w-min"

            SizeMax ->
                "w-max"

            SizeZero ->
                "w-0"

            S1_5 ->
                "w-1.5"

            S3 ->
                "w-3"

            S4 ->
                "w-4"

            S6 ->
                "w-6"

            S7 ->
                "w-7"

            S9 ->
                "w-9"

            S10 ->
                "w-10"

            S11 ->
                "w-11"

            S12 ->
                "w-12"

            S14 ->
                "w-14"

            S16 ->
                "w-16"

            S20 ->
                "w-20"
        )

withHeight : Size -> Config Config.Standard -> Config Config.Standard
withHeight v =
    Config.set "height"
        (case v of
            SizeFull ->
                "h-full"

            SizeAuto ->
                "h-auto"

            SizeScreen ->
                "h-screen"

            SizeFit ->
                "h-fit"

            SizeMin ->
                "h-min"

            SizeMax ->
                "h-max"

            SizeZero ->
                "h-0"

            S1_5 ->
                "h-1.5"

            S3 ->
                "h-3"

            S4 ->
                "h-4"

            S6 ->
                "h-6"

            S7 ->
                "h-7"

            S9 ->
                "h-9"

            S10 ->
                "h-10"

            S11 ->
                "h-11"

            S12 ->
                "h-12"

            S14 ->
                "h-14"

            S16 ->
                "h-16"

            S20 ->
                "h-20"
        )

withMinWidth : Size -> Config Config.Standard -> Config Config.Standard
withMinWidth v =
    Config.set "min-width"
        (case v of
            SizeFull ->
                "min-w-full"

            SizeAuto ->
                "min-w-auto"

            SizeScreen ->
                "min-w-screen"

            SizeFit ->
                "min-w-fit"

            SizeMin ->
                "min-w-min"

            SizeMax ->
                "min-w-max"

            SizeZero ->
                "min-w-0"

            S1_5 ->
                "min-w-1.5"

            S3 ->
                "min-w-3"

            S4 ->
                "min-w-4"

            S6 ->
                "min-w-6"

            S7 ->
                "min-w-7"

            S9 ->
                "min-w-9"

            S10 ->
                "min-w-10"

            S11 ->
                "min-w-11"

            S12 ->
                "min-w-12"

            S14 ->
                "min-w-14"

            S16 ->
                "min-w-16"

            S20 ->
                "min-w-20"
        )

withMinHeight : Size -> Config Config.Standard -> Config Config.Standard
withMinHeight v =
    Config.set "min-height"
        (case v of
            SizeFull ->
                "min-h-full"

            SizeAuto ->
                "min-h-auto"

            SizeScreen ->
                "min-h-screen"

            SizeFit ->
                "min-h-fit"

            SizeMin ->
                "min-h-min"

            SizeMax ->
                "min-h-max"

            SizeZero ->
                "min-h-0"

            S1_5 ->
                "min-h-1.5"

            S3 ->
                "min-h-3"

            S4 ->
                "min-h-4"

            S6 ->
                "min-h-6"

            S7 ->
                "min-h-7"

            S9 ->
                "min-h-9"

            S10 ->
                "min-h-10"

            S11 ->
                "min-h-11"

            S12 ->
                "min-h-12"

            S14 ->
                "min-h-14"

            S16 ->
                "min-h-16"

            S20 ->
                "min-h-20"
        )

withMaxWidth : Size -> Config Config.Standard -> Config Config.Standard
withMaxWidth v =
    Config.set "max-width"
        (case v of
            SizeFull ->
                "max-w-full"

            SizeAuto ->
                "max-w-none"

            SizeScreen ->
                "max-w-screen"

            SizeFit ->
                "max-w-fit"

            SizeMin ->
                "max-w-min"

            SizeMax ->
                "max-w-max"

            SizeZero ->
                "max-w-0"

            S1_5 ->
                "max-w-1.5"

            S3 ->
                "max-w-3"

            S4 ->
                "max-w-4"

            S6 ->
                "max-w-6"

            S7 ->
                "max-w-7"

            S9 ->
                "max-w-9"

            S10 ->
                "max-w-10"

            S11 ->
                "max-w-11"

            S12 ->
                "max-w-12"

            S14 ->
                "max-w-14"

            S16 ->
                "max-w-16"

            S20 ->
                "max-w-20"
        )

type BorderWidth
    = BorderNone
    | BorderThin
    | BorderThick

withBorderWidth : BorderWidth -> Config tag -> Config tag
withBorderWidth v =
    Config.set "border-width"
        (case v of
            BorderNone ->
                "border-0"

            BorderThin ->
                "border"

            BorderThick ->
                "border-2"
        )

type FlexBasis
    = BasisZero
    | BasisAuto

withFlexBasis : FlexBasis -> Config Config.Standard -> Config Config.Standard
withFlexBasis v =
    Config.set "basis"
        (case v of
            BasisZero ->
                "basis-0"

            BasisAuto ->
                "basis-auto"
        )

type AspectRatio
    = AspectSquare

withAspectRatio : AspectRatio -> Config Config.Standard -> Config Config.Standard
withAspectRatio v =
    Config.set "aspect"
        (case v of
            AspectSquare ->
                "aspect-square"
        )

withGrow : Bool -> Config Config.Standard -> Config Config.Standard
withGrow grow =
    Config.set "grow"
        (if grow then
            "grow"

         else
            "grow-0"
        )

withShrink : Bool -> Config Config.Standard -> Config Config.Standard
withShrink shrink =
    Config.set "shrink"
        (if shrink then
            "shrink"

         else
            "shrink-0"
        )

{-| Set width and height to the same size. -}
square : Size -> Config Config.Standard -> Config Config.Standard
square s =
    withWidth s >> withHeight s

withBorderSide : Edge -> Config tag -> Config tag
withBorderSide edge =
    let
        ( key, cls ) =
            case edge of
                Space.Top ->
                    ( "border-t", "border-t" )

                Space.Right ->
                    ( "border-r", "border-r" )

                Space.Bottom ->
                    ( "border-b", "border-b" )

                Space.Left ->
                    ( "border-l", "border-l" )

                _ ->
                    ( "border-side", "border" )
    in
    Config.set key cls

withControlHeight : Config Config.Standard -> Config Config.Standard
withControlHeight =
    Config.set "height" "h-[34px]"

controlSquare : Config Config.Standard -> Config Config.Standard
controlSquare =
    Config.set "width" "w-[34px]" >> Config.set "height" "h-[34px]"

withFlexWrap : Bool -> Config Config.Standard -> Config Config.Standard
withFlexWrap wrap =
    Config.set "flex-wrap"
        (if wrap then
            "flex-wrap"

         else
            "flex-nowrap"
        )

withCenterX : Config Config.Standard -> Config Config.Standard
withCenterX =
    Config.set "mx" "mx-auto"
