-- GENERATED by codegen/generate.js — do not edit by hand.
module Tebru.Theme.Surface exposing (Surface(..), surfaceToClass, withSurface, withSurfaceCustom)

{-| Generated token module — do not edit by hand.
To change a token, edit the tokens file and regenerate (codegen/generate.js).

@docs Surface, surfaceToClass, withSurface, withSurfaceCustom

-}

import Tebru.Theme.Config as Config exposing (Config)


type Surface a
    = Page
    | Card
    | CardAlt
    | Subtle
    | Selected
    | Disabled
    | Brand
    | BrandHover
    | Danger
    | DangerHover
    | Success
    | Warning
    | Info
    | Error
    | Inverse
    | InverseHover
    | InverseActive
    | Backdrop
    | Transparent
    | Custom a

surfaceToClass : (a -> String) -> Surface a -> String
surfaceToClass toCustom v =
    case v of
        Page ->
            "bg-surface-page"

        Card ->
            "bg-surface-card"

        CardAlt ->
            "bg-surface-card-alt"

        Subtle ->
            "bg-surface-subtle"

        Selected ->
            "bg-surface-selected"

        Disabled ->
            "bg-surface-disabled"

        Brand ->
            "bg-surface-brand"

        BrandHover ->
            "bg-surface-brand-hover"

        Danger ->
            "bg-surface-danger"

        DangerHover ->
            "bg-surface-danger-hover"

        Success ->
            "bg-surface-success"

        Warning ->
            "bg-surface-warning"

        Info ->
            "bg-surface-info"

        Error ->
            "bg-surface-error"

        Inverse ->
            "bg-surface-inverse"

        InverseHover ->
            "bg-surface-inverse-hover"

        InverseActive ->
            "bg-surface-inverse-active"

        Backdrop ->
            "bg-surface-backdrop"

        Transparent ->
            "bg-transparent"

        Custom a ->
            toCustom a

withSurfaceCustom : (a -> String) -> Surface a -> Config tag -> Config tag
withSurfaceCustom toCustom v =
    Config.set "surface" (surfaceToClass toCustom v)


withSurface : Surface Never -> Config tag -> Config tag
withSurface =
    withSurfaceCustom never
