-- GENERATED by codegen/generate.js — do not edit by hand.
module Tebru.Theme.Text exposing (Text(..), textToClass, withText, withTextCustom)

{-| Generated token module — do not edit by hand.
To change a token, edit the tokens file and regenerate (codegen/generate.js).

@docs Text, textToClass, withText, withTextCustom

-}

import Tebru.Theme.Config as Config exposing (Config)


type Text a
    = Default
    | Secondary
    | Muted
    | Hint
    | Inverse
    | InverseMuted
    | OnBrand
    | Link
    | LinkHover
    | Error
    | Success
    | Custom a

textToClass : (a -> String) -> Text a -> String
textToClass toCustom v =
    case v of
        Default ->
            "text-fg-default"

        Secondary ->
            "text-fg-secondary"

        Muted ->
            "text-fg-muted"

        Hint ->
            "text-fg-hint"

        Inverse ->
            "text-fg-inverse"

        InverseMuted ->
            "text-fg-inverse-muted"

        OnBrand ->
            "text-fg-on-brand"

        Link ->
            "text-fg-link"

        LinkHover ->
            "text-fg-link-hover"

        Error ->
            "text-fg-error"

        Success ->
            "text-fg-success"

        Custom a ->
            toCustom a

withTextCustom : (a -> String) -> Text a -> Config tag -> Config tag
withTextCustom toCustom v =
    Config.set "text" (textToClass toCustom v)


withText : Text Never -> Config tag -> Config tag
withText =
    withTextCustom never
