-- GENERATED by codegen/generate.js — do not edit by hand.
module Tebru.Theme.Transition exposing (Transition(..), transitionToClass, withTransition, Duration(..), durationToClass, withDuration, Easing(..), easingToClass, withEasing)

{-| Generated token module — do not edit by hand.
To change a token, edit the tokens file and regenerate (codegen/generate.js).

@docs Transition, transitionToClass, withTransition, Duration, durationToClass, withDuration, Easing
@docs easingToClass, withEasing

-}

import Tebru.Theme.Config as Config exposing (Config)


type Transition
    = TransitionColors
    | TransitionAll
    | TransitionOpacity
    | TransitionTransform
    | TransitionShadow
    | TransitionWidth
    | TransitionNone

transitionToClass : Transition -> String
transitionToClass v =
    case v of
        TransitionColors ->
            "transition-colors"

        TransitionAll ->
            "transition-all"

        TransitionOpacity ->
            "transition-opacity"

        TransitionTransform ->
            "transition-transform"

        TransitionShadow ->
            "transition-shadow"

        TransitionWidth ->
            "transition-[width]"

        TransitionNone ->
            "transition-none"

withTransition : Transition -> Config Config.Standard -> Config Config.Standard
withTransition v =
    Config.set "transition" (transitionToClass v)

type Duration
    = DurationFast
    | DurationNormal
    | DurationSlow

durationToClass : Duration -> String
durationToClass v =
    case v of
        DurationFast ->
            "duration-75"

        DurationNormal ->
            "duration-150"

        DurationSlow ->
            "duration-300"

withDuration : Duration -> Config Config.Standard -> Config Config.Standard
withDuration v =
    Config.set "duration" (durationToClass v)

type Easing
    = EaseLinear
    | EaseIn
    | EaseOut
    | EaseInOut

easingToClass : Easing -> String
easingToClass v =
    case v of
        EaseLinear ->
            "ease-linear"

        EaseIn ->
            "ease-in"

        EaseOut ->
            "ease-out"

        EaseInOut ->
            "ease-in-out"

withEasing : Easing -> Config Config.Standard -> Config Config.Standard
withEasing v =
    Config.set "easing" (easingToClass v)
