-- GENERATED by codegen/generate.js — do not edit by hand.
module Tebru.Theme.Typography exposing (FontSize(..), fontSizeToClass, withFontSize, withFontSizeCustom, FontWeight(..), fontWeightToClass, withFontWeight, withFontWeightCustom, TextAlign(..), textAlignToClass, withTextAlign, LetterSpacing(..), letterSpacingToClass, withLetterSpacing, LineHeight(..), lineHeightToClass, withLineHeight, WhiteSpace(..), whiteSpaceToClass, withWhiteSpace, TextTransform(..), textTransformToClass, withTextTransform, Decoration(..), decorationToClass, withDecoration, TextOverflow(..), textOverflowToClass, withTextOverflow)

{-| Generated token module — do not edit by hand.
To change a token, edit the tokens file and regenerate (codegen/generate.js).

@docs FontSize, fontSizeToClass, withFontSize, withFontSizeCustom, FontWeight, fontWeightToClass
@docs withFontWeight, withFontWeightCustom, TextAlign, textAlignToClass, withTextAlign, LetterSpacing
@docs letterSpacingToClass, withLetterSpacing, LineHeight, lineHeightToClass, withLineHeight, WhiteSpace
@docs whiteSpaceToClass, withWhiteSpace, TextTransform, textTransformToClass, withTextTransform, Decoration
@docs decorationToClass, withDecoration, TextOverflow, textOverflowToClass, withTextOverflow

-}

import Tebru.Theme.Config as Config exposing (Config)


type FontSize a
    = Xxs
    | Xs
    | Sm
    | Base
    | Lg
    | Xl
    | X2l
    | X3l
    | FontSizeCustom a

fontSizeToClass : (a -> String) -> FontSize a -> String
fontSizeToClass toCustom v =
    case v of
        Xxs ->
            "text-xxs"

        Xs ->
            "text-xs"

        Sm ->
            "text-sm"

        Base ->
            "text-base"

        Lg ->
            "text-lg"

        Xl ->
            "text-xl"

        X2l ->
            "text-2xl"

        X3l ->
            "text-3xl"

        FontSizeCustom a ->
            toCustom a

withFontSizeCustom : (a -> String) -> FontSize a -> Config Config.Standard -> Config Config.Standard
withFontSizeCustom toCustom v =
    Config.set "fontSize" (fontSizeToClass toCustom v)


withFontSize : FontSize Never -> Config Config.Standard -> Config Config.Standard
withFontSize =
    withFontSizeCustom never

type FontWeight a
    = Normal
    | Medium
    | Semibold
    | Bold
    | FontWeightCustom a

fontWeightToClass : (a -> String) -> FontWeight a -> String
fontWeightToClass toCustom v =
    case v of
        Normal ->
            "font-normal"

        Medium ->
            "font-medium"

        Semibold ->
            "font-semibold"

        Bold ->
            "font-bold"

        FontWeightCustom a ->
            toCustom a

withFontWeightCustom : (a -> String) -> FontWeight a -> Config Config.Standard -> Config Config.Standard
withFontWeightCustom toCustom v =
    Config.set "fontWeight" (fontWeightToClass toCustom v)


withFontWeight : FontWeight Never -> Config Config.Standard -> Config Config.Standard
withFontWeight =
    withFontWeightCustom never

type TextAlign
    = TextLeft
    | TextCenter
    | TextRight

textAlignToClass : TextAlign -> String
textAlignToClass v =
    case v of
        TextLeft ->
            "text-left"

        TextCenter ->
            "text-center"

        TextRight ->
            "text-right"

withTextAlign : TextAlign -> Config Config.Standard -> Config Config.Standard
withTextAlign v =
    Config.set "textAlign" (textAlignToClass v)

type LetterSpacing
    = TrackingTight
    | TrackingNormal
    | TrackingWide

letterSpacingToClass : LetterSpacing -> String
letterSpacingToClass v =
    case v of
        TrackingTight ->
            "tracking-tight"

        TrackingNormal ->
            "tracking-normal"

        TrackingWide ->
            "tracking-wide"

withLetterSpacing : LetterSpacing -> Config Config.Standard -> Config Config.Standard
withLetterSpacing v =
    Config.set "letterSpacing" (letterSpacingToClass v)

type LineHeight
    = LineNone
    | LineTight

lineHeightToClass : LineHeight -> String
lineHeightToClass v =
    case v of
        LineNone ->
            "leading-none"

        LineTight ->
            "leading-tight"

withLineHeight : LineHeight -> Config Config.Standard -> Config Config.Standard
withLineHeight v =
    Config.set "lineHeight" (lineHeightToClass v)

type WhiteSpace
    = WhiteSpaceNormal
    | WhiteSpaceNowrap

whiteSpaceToClass : WhiteSpace -> String
whiteSpaceToClass v =
    case v of
        WhiteSpaceNormal ->
            "whitespace-normal"

        WhiteSpaceNowrap ->
            "whitespace-nowrap"

withWhiteSpace : WhiteSpace -> Config Config.Standard -> Config Config.Standard
withWhiteSpace v =
    Config.set "whiteSpace" (whiteSpaceToClass v)

type TextTransform
    = Uppercase

textTransformToClass : TextTransform -> String
textTransformToClass v =
    case v of
        Uppercase ->
            "uppercase"

withTextTransform : TextTransform -> Config Config.Standard -> Config Config.Standard
withTextTransform v =
    Config.set "textTransform" (textTransformToClass v)

type Decoration
    = Underline
    | NoUnderline

decorationToClass : Decoration -> String
decorationToClass v =
    case v of
        Underline ->
            "underline"

        NoUnderline ->
            "no-underline"

withDecoration : Decoration -> Config tag -> Config tag
withDecoration v =
    Config.set "decoration" (decorationToClass v)

type TextOverflow
    = Truncate

textOverflowToClass : TextOverflow -> String
textOverflowToClass v =
    case v of
        Truncate ->
            "truncate"

withTextOverflow : TextOverflow -> Config Config.Standard -> Config Config.Standard
withTextOverflow v =
    Config.set "textOverflow" (textOverflowToClass v)
