const fs = require("fs");
const path = require("path");

const RESERVED = new Set([
  "type", "alias", "port", "module", "exposing", "import", "as",
  "if", "then", "else", "case", "of", "let", "in", "where", "infix", "main"
]);

function elmName(lucide) {
  let n = lucide.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
  if (/^[0-9]/.test(n)) n = "n" + n.charAt(0).toUpperCase() + n.slice(1);
  if (RESERVED.has(n)) n = n + "_";
  return n;
}

function attrKey(k) {
  return { "stroke-width": "strokeWidth", "stroke-linecap": "strokeLinecap", "stroke-linejoin": "strokeLinejoin" }[k]
    || k.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

// nodes: [[tag, attrsObject], …] straight from icon-nodes.json
function nodesFromData(nodes) {
  return nodes.map(([tag, attrs]) => {
    const pairs = Object.entries(attrs).map(([k, v]) => `SA.${attrKey(k)} "${v}"`);
    return `Svg.${tag} [ ${pairs.join(", ")} ] []`;
  });
}

function elmValueFor(name, nodes) {
  const items = nodesFromData(nodes).join("\n    , ");
  return `${name} : List (Svg.Svg msg)\n${name} =\n    [ ${items}\n    ]`;
}

function writeGeometry(outPath) {
  const iconNodes = require("lucide-static/icon-nodes.json");  // { "a-arrow-down": [[tag, attrs], …], … }
  const seen = new Map();
  const values = Object.entries(iconNodes).map(([lucideName, nodes]) => {
    let name = elmName(lucideName);
    if (seen.has(name)) { const n = seen.get(name) + 1; seen.set(name, n); name = name + String(n); } else seen.set(name, 1);
    return elmValueFor(name, nodes);
  });
  const header = "-- GENERATED by codegen/generate-icons.js from lucide-static/icon-nodes.json — do not edit.\nmodule Tebru.Icon.Geometry exposing (..)\n\nimport Svg\nimport Svg.Attributes as SA\n";
  fs.writeFileSync(outPath, header + "\n\n" + values.join("\n\n\n") + "\n");
  return values.length;
}

if (require.main === module) {
  const count = writeGeometry(path.join(__dirname, "..", "src", "Tebru", "Icon", "Geometry.elm"));
  console.log(`Generated ${count} icon values in src/Tebru/Icon/Geometry.elm`);
}

module.exports = { elmName, elmValueFor, nodesFromData, attrKey, writeGeometry, RESERVED };
