module Theme.StructureParityTest exposing (suite)

{-| Class-parity lock for Tebru.Theme.Structure and the Tebru.Box grid-cols
matrix: every setter x variant must resolve to exactly the class it emitted
before the module became generated (ticket frontend-9bf.16). Written against the
old hand-written module and kept as a regression guard for the generator.
-}

import Expect
import Tebru.Box as Layout
import Tebru.Theme.Config as Config
import Tebru.Theme.Space as Space
import Tebru.Theme.Structure as Structure
import Test exposing (Test, describe, test)


structureCases : List ( String, Config.Config Config.Standard -> Config.Config Config.Standard )
structureCases =
    [ ( "border-solid", Structure.withBorderStyle Structure.BorderSolid )
    , ( "border-dashed", Structure.withBorderStyle Structure.BorderDashed )
    , ( "border-dotted", Structure.withBorderStyle Structure.BorderDotted )
    , ( "block", Structure.withDisplay Structure.Block )
    , ( "flex", Structure.withDisplay Structure.Flex )
    , ( "inline-flex", Structure.withDisplay Structure.InlineFlex )
    , ( "inline-block", Structure.withDisplay Structure.InlineBlock )
    , ( "grid", Structure.withDisplay Structure.Grid )
    , ( "hidden", Structure.withDisplay Structure.None )
    , ( "justify-start", Structure.withJustify Structure.JustifyStart )
    , ( "justify-center", Structure.withJustify Structure.JustifyCenter )
    , ( "justify-end", Structure.withJustify Structure.JustifyEnd )
    , ( "justify-between", Structure.withJustify Structure.JustifyBetween )
    , ( "items-start", Structure.withAlign Structure.AlignStart )
    , ( "items-center", Structure.withAlign Structure.AlignCenter )
    , ( "items-end", Structure.withAlign Structure.AlignEnd )
    , ( "items-stretch", Structure.withAlign Structure.AlignStretch )
    , ( "cursor-pointer", Structure.withCursor Structure.CursorPointer )
    , ( "cursor-default", Structure.withCursor Structure.CursorDefault )
    , ( "cursor-grab", Structure.withCursor Structure.CursorGrab )
    , ( "cursor-ns-resize", Structure.withCursor Structure.CursorNsResize )
    , ( "static", Structure.withPosition Structure.Static )
    , ( "relative", Structure.withPosition Structure.Relative )
    , ( "absolute", Structure.withPosition Structure.Absolute )
    , ( "fixed", Structure.withPosition Structure.Fixed )
    , ( "sticky", Structure.withPosition Structure.Sticky )
    , ( "inset-0", Structure.withInset Structure.Inset0 )
    , ( "inset-auto", Structure.withInset Structure.InsetAuto )
    , ( "z-0", Structure.withZ Structure.ZBase )
    , ( "z-10", Structure.withZ Structure.ZRaised )
    , ( "z-20", Structure.withZ Structure.ZSticky )
    , ( "z-30", Structure.withZ Structure.ZDropdown )
    , ( "z-40", Structure.withZ Structure.ZOverlay )
    , ( "z-50", Structure.withZ Structure.ZModal )
    , ( "opacity-0", Structure.withOpacity Structure.Opacity0 )
    , ( "opacity-50", Structure.withOpacity Structure.Opacity50 )
    , ( "opacity-60", Structure.withOpacity Structure.Opacity60 )
    , ( "opacity-100", Structure.withOpacity Structure.Opacity100 )
    , ( "overflow-visible", Structure.withOverflow Structure.OverflowVisible )
    , ( "overflow-hidden", Structure.withOverflow Structure.OverflowHidden )
    , ( "overflow-auto", Structure.withOverflow Structure.OverflowAuto )
    , ( "overflow-scroll", Structure.withOverflow Structure.OverflowScroll )
    , ( "overflow-x-visible", Structure.withOverflowX Structure.OverflowVisible )
    , ( "overflow-x-hidden", Structure.withOverflowX Structure.OverflowHidden )
    , ( "overflow-x-auto", Structure.withOverflowX Structure.OverflowAuto )
    , ( "overflow-x-scroll", Structure.withOverflowX Structure.OverflowScroll )
    , ( "overflow-y-visible", Structure.withOverflowY Structure.OverflowVisible )
    , ( "overflow-y-hidden", Structure.withOverflowY Structure.OverflowHidden )
    , ( "overflow-y-auto", Structure.withOverflowY Structure.OverflowAuto )
    , ( "overflow-y-scroll", Structure.withOverflowY Structure.OverflowScroll )
    , ( "pointer-events-none", Structure.withPointerEvents Structure.PointerNone )
    , ( "pointer-events-auto", Structure.withPointerEvents Structure.PointerAuto )
    , ( "flex-1", Structure.withFlex Structure.Flex1 )
    , ( "flex-auto", Structure.withFlex Structure.FlexAuto )
    , ( "flex-initial", Structure.withFlex Structure.FlexInitial )
    , ( "flex-none", Structure.withFlex Structure.FlexNone )
    , ( "w-full", Structure.withWidth Structure.SizeFull )
    , ( "w-auto", Structure.withWidth Structure.SizeAuto )
    , ( "w-screen", Structure.withWidth Structure.SizeScreen )
    , ( "w-fit", Structure.withWidth Structure.SizeFit )
    , ( "w-min", Structure.withWidth Structure.SizeMin )
    , ( "w-max", Structure.withWidth Structure.SizeMax )
    , ( "w-0", Structure.withWidth Structure.SizeZero )
    , ( "w-1.5", Structure.withWidth Structure.S1_5 )
    , ( "w-3", Structure.withWidth Structure.S3 )
    , ( "w-4", Structure.withWidth Structure.S4 )
    , ( "w-6", Structure.withWidth Structure.S6 )
    , ( "w-7", Structure.withWidth Structure.S7 )
    , ( "w-9", Structure.withWidth Structure.S9 )
    , ( "w-10", Structure.withWidth Structure.S10 )
    , ( "w-11", Structure.withWidth Structure.S11 )
    , ( "w-12", Structure.withWidth Structure.S12 )
    , ( "w-14", Structure.withWidth Structure.S14 )
    , ( "w-16", Structure.withWidth Structure.S16 )
    , ( "w-20", Structure.withWidth Structure.S20 )
    , ( "h-full", Structure.withHeight Structure.SizeFull )
    , ( "h-auto", Structure.withHeight Structure.SizeAuto )
    , ( "h-screen", Structure.withHeight Structure.SizeScreen )
    , ( "h-fit", Structure.withHeight Structure.SizeFit )
    , ( "h-min", Structure.withHeight Structure.SizeMin )
    , ( "h-max", Structure.withHeight Structure.SizeMax )
    , ( "h-0", Structure.withHeight Structure.SizeZero )
    , ( "h-1.5", Structure.withHeight Structure.S1_5 )
    , ( "h-3", Structure.withHeight Structure.S3 )
    , ( "h-4", Structure.withHeight Structure.S4 )
    , ( "h-6", Structure.withHeight Structure.S6 )
    , ( "h-7", Structure.withHeight Structure.S7 )
    , ( "h-9", Structure.withHeight Structure.S9 )
    , ( "h-10", Structure.withHeight Structure.S10 )
    , ( "h-11", Structure.withHeight Structure.S11 )
    , ( "h-12", Structure.withHeight Structure.S12 )
    , ( "h-14", Structure.withHeight Structure.S14 )
    , ( "h-16", Structure.withHeight Structure.S16 )
    , ( "h-20", Structure.withHeight Structure.S20 )
    , ( "min-w-full", Structure.withMinWidth Structure.SizeFull )
    , ( "min-w-auto", Structure.withMinWidth Structure.SizeAuto )
    , ( "min-w-screen", Structure.withMinWidth Structure.SizeScreen )
    , ( "min-w-fit", Structure.withMinWidth Structure.SizeFit )
    , ( "min-w-min", Structure.withMinWidth Structure.SizeMin )
    , ( "min-w-max", Structure.withMinWidth Structure.SizeMax )
    , ( "min-w-0", Structure.withMinWidth Structure.SizeZero )
    , ( "min-w-1.5", Structure.withMinWidth Structure.S1_5 )
    , ( "min-w-3", Structure.withMinWidth Structure.S3 )
    , ( "min-w-4", Structure.withMinWidth Structure.S4 )
    , ( "min-w-6", Structure.withMinWidth Structure.S6 )
    , ( "min-w-7", Structure.withMinWidth Structure.S7 )
    , ( "min-w-9", Structure.withMinWidth Structure.S9 )
    , ( "min-w-10", Structure.withMinWidth Structure.S10 )
    , ( "min-w-11", Structure.withMinWidth Structure.S11 )
    , ( "min-w-12", Structure.withMinWidth Structure.S12 )
    , ( "min-w-14", Structure.withMinWidth Structure.S14 )
    , ( "min-w-16", Structure.withMinWidth Structure.S16 )
    , ( "min-w-20", Structure.withMinWidth Structure.S20 )
    , ( "min-h-full", Structure.withMinHeight Structure.SizeFull )
    , ( "min-h-auto", Structure.withMinHeight Structure.SizeAuto )
    , ( "min-h-screen", Structure.withMinHeight Structure.SizeScreen )
    , ( "min-h-fit", Structure.withMinHeight Structure.SizeFit )
    , ( "min-h-min", Structure.withMinHeight Structure.SizeMin )
    , ( "min-h-max", Structure.withMinHeight Structure.SizeMax )
    , ( "min-h-0", Structure.withMinHeight Structure.SizeZero )
    , ( "min-h-1.5", Structure.withMinHeight Structure.S1_5 )
    , ( "min-h-3", Structure.withMinHeight Structure.S3 )
    , ( "min-h-4", Structure.withMinHeight Structure.S4 )
    , ( "min-h-6", Structure.withMinHeight Structure.S6 )
    , ( "min-h-7", Structure.withMinHeight Structure.S7 )
    , ( "min-h-9", Structure.withMinHeight Structure.S9 )
    , ( "min-h-10", Structure.withMinHeight Structure.S10 )
    , ( "min-h-11", Structure.withMinHeight Structure.S11 )
    , ( "min-h-12", Structure.withMinHeight Structure.S12 )
    , ( "min-h-14", Structure.withMinHeight Structure.S14 )
    , ( "min-h-16", Structure.withMinHeight Structure.S16 )
    , ( "min-h-20", Structure.withMinHeight Structure.S20 )
    , ( "max-w-full", Structure.withMaxWidth Structure.SizeFull )

    -- Intentional post-parity fix: the pre-refactor literal was `max-w-auto`,
    -- which is not a real utility (CSS max-width has no `auto`) and silently
    -- emitted nothing. `max-w-none` is the real escape.
    , ( "max-w-none", Structure.withMaxWidth Structure.SizeAuto )
    , ( "max-w-screen", Structure.withMaxWidth Structure.SizeScreen )
    , ( "max-w-fit", Structure.withMaxWidth Structure.SizeFit )
    , ( "max-w-min", Structure.withMaxWidth Structure.SizeMin )
    , ( "max-w-max", Structure.withMaxWidth Structure.SizeMax )
    , ( "max-w-0", Structure.withMaxWidth Structure.SizeZero )
    , ( "max-w-1.5", Structure.withMaxWidth Structure.S1_5 )
    , ( "max-w-3", Structure.withMaxWidth Structure.S3 )
    , ( "max-w-4", Structure.withMaxWidth Structure.S4 )
    , ( "max-w-6", Structure.withMaxWidth Structure.S6 )
    , ( "max-w-7", Structure.withMaxWidth Structure.S7 )
    , ( "max-w-9", Structure.withMaxWidth Structure.S9 )
    , ( "max-w-10", Structure.withMaxWidth Structure.S10 )
    , ( "max-w-11", Structure.withMaxWidth Structure.S11 )
    , ( "max-w-12", Structure.withMaxWidth Structure.S12 )
    , ( "max-w-14", Structure.withMaxWidth Structure.S14 )
    , ( "max-w-16", Structure.withMaxWidth Structure.S16 )
    , ( "max-w-20", Structure.withMaxWidth Structure.S20 )
    , ( "border-0", Structure.withBorderWidth Structure.BorderNone )
    , ( "border", Structure.withBorderWidth Structure.BorderThin )
    , ( "border-2", Structure.withBorderWidth Structure.BorderThick )
    , ( "basis-0", Structure.withFlexBasis Structure.BasisZero )
    , ( "basis-auto", Structure.withFlexBasis Structure.BasisAuto )
    , ( "aspect-square", Structure.withAspectRatio Structure.AspectSquare )
    , ( "grow", Structure.withGrow True )
    , ( "grow-0", Structure.withGrow False )
    , ( "shrink", Structure.withShrink True )
    , ( "shrink-0", Structure.withShrink False )
    , ( "flex-wrap", Structure.withFlexWrap True )
    , ( "flex-nowrap", Structure.withFlexWrap False )
    , ( "border-t", Structure.withBorderSide Space.Top )
    , ( "border-r", Structure.withBorderSide Space.Right )
    , ( "border-b", Structure.withBorderSide Space.Bottom )
    , ( "border-l", Structure.withBorderSide Space.Left )
    , ( "border", Structure.withBorderSide Space.All )
    , ( "h-[34px]", Structure.withControlHeight )
    , ( "h-[34px] w-[34px]", Structure.controlSquare )
    , ( "mx-auto", Structure.withCenterX )
    , ( "h-full w-full", Structure.square Structure.SizeFull )
    , ( "h-10 w-10", Structure.square Structure.S10 )
    ]


gridColsCases : List ( Int, String )
gridColsCases =
    [ ( 0, "grid-cols-1 md:grid-cols-1 lg:grid-cols-1 xl:grid-cols-1 grid" )
    , ( 1, "grid-cols-1 md:grid-cols-1 lg:grid-cols-1 xl:grid-cols-1 grid" )
    , ( 2, "grid-cols-2 md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-2 grid" )
    , ( 3, "grid-cols-3 md:grid-cols-3 lg:grid-cols-3 xl:grid-cols-3 grid" )
    , ( 4, "grid-cols-4 md:grid-cols-4 lg:grid-cols-4 xl:grid-cols-4 grid" )
    , ( 5, "grid-cols-5 md:grid-cols-5 lg:grid-cols-5 xl:grid-cols-5 grid" )
    , ( 6, "grid-cols-6 md:grid-cols-6 lg:grid-cols-6 xl:grid-cols-6 grid" )
    , ( 7, "grid-cols-7 md:grid-cols-7 lg:grid-cols-7 xl:grid-cols-7 grid" )
    , ( 8, "grid-cols-8 md:grid-cols-8 lg:grid-cols-8 xl:grid-cols-8 grid" )
    , ( 9, "grid-cols-9 md:grid-cols-9 lg:grid-cols-9 xl:grid-cols-9 grid" )
    , ( 10, "grid-cols-10 md:grid-cols-10 lg:grid-cols-10 xl:grid-cols-10 grid" )
    , ( 11, "grid-cols-11 md:grid-cols-11 lg:grid-cols-11 xl:grid-cols-11 grid" )
    , ( 12, "grid-cols-12 md:grid-cols-12 lg:grid-cols-12 xl:grid-cols-12 grid" )
    , ( 13, "grid-cols-1 md:grid-cols-1 lg:grid-cols-1 xl:grid-cols-1 grid" )
    ]


suite : Test
suite =
    describe "Structure class parity"
        [ describe "setter x variant resolves to the pre-refactor literal class"
            (List.indexedMap
                (\i ( expected, setter ) ->
                    test (String.fromInt i ++ ": " ++ expected) <|
                        \_ -> Config.default |> setter |> Config.toClasses |> Expect.equal expected
                )
                structureCases
            )
        , describe "grid-cols matrix resolves every breakpoint arm"
            (List.map
                (\( n, expected ) ->
                    test ("cols " ++ String.fromInt n) <|
                        \_ ->
                            Layout.grid Space.None []
                                |> Layout.withGridCols { sm = n, md = n, lg = n, xl = n }
                                |> Layout.toClasses
                                |> Expect.equal expected
                )
                gridColsCases
            )
        ]
